workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
    
    

scripts:
  - name: Force migrate MainActivity to V2
    script: |
      rm -f android/app/src/main/java/com/panconowallet/MainActivity.java
      mkdir -p android/app/src/main/kotlin/com/panconowallet
      cat > android/app/src/main/kotlin/com/panconowallet/MainActivity.kt <<'EOF'
      package com.panconowallet

      import io.flutter.embedding.android.FlutterActivity

      class MainActivity: FlutterActivity() {
      }
      EOF

