workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
    
    scripts:
      - name: Clean project
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --debug
    
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    
    publishing:
      email:
        recipients:
          - "olvinds91@gmail.com"
