workflows:
  pancono_wallet:
    name: Pancono Wallet Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        # Optional: Add environment variables here
    scripts:
      - name: Pre-build
        script: |
          echo "Cleaning old builds..."
          flutter clean
          echo "Fetching dependencies..."
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
